package com.mypooja.androidapp.FindPujari.View.PujariListing;

/**
 * Created by vinayhuddar on 08/09/15.
 */
public class DummyFilterOptions {
    public static final String[] areaNames = {
        "Abbigere",
        "Adugodi",
        "AECS Layout",
        "Akshayanagar",
        "Amrutha Halli",
        "Anagalapura",
        "Andrahalli",
        "Anekal",
        "Anjanapura",
        "Annapurneshwari Nagar",
        "Arekere",
        "Ashok Nagar",
        "Attibele",
        "Attiguppe",
        "Azad Nagar",
        "Babusa Palya",
        "Bagalakunte",
        "Bagaluru",
        "Bagepalli",
        "Baiyyappanahalli",
        "Banashankari",
        "Banaswadi",
        "Bannerghatta",
        "Bannerghatta Road",
        "Bapuji Nagar",
        "Basapura",
        "Basavanagar",
        "Basavanagudi",
        "Basavanna Nagar",
        "Basaveshwara Nagar",
        "Battarahalli",
        "Begur",
        "Begur Road",
        "Belathur",
        "Bellandur",
        "Bellandur Outer Ring Road",
        "Bellary Road",
        "BEML Layout",
        "BEML Layout Raja Rajeshwari Nagar",
        "Bennigana Halli",
        "Benson Town",
        "Bettahalasur",
        "Bhuvaneshwari Nagar",
        "Bidadi",
        "Bidrahalli",
        "Bikkanahalli",
        "Bilekahalli",
        "Bommanahalli",
        "Bommasandra",
        "Bommenahalli",
        "Brigade Road",
        "Brookefield",
        "BTM Layout",
        "BTM Layout",
        "Budigere",
        "Cambridge Layout",
        "Chamarajpet",
        "Chandapura",
        "Chandapura Anekal Road",
        "Chandra Layout",
        "Channasandra",
        "Chickpet",
        "Chikbanavara",
        "Chikka Tirupathi",
        "Chikkaballapur",
        "Chikkaballapur-Gauribidanur Road",
        "Chikkabidarakallu",
        "Chikkajala",
        "Chikkalasandra",
        "Chikkanahalli",
        "Chintamani",
        "Choodasandra",
        "Commercial Street",
        "Cooke Town",
        "Cottonpete",
        "Cox Town",
        "Cunningham Road",
        "CV Raman Nagar",
        "Dabaspete",
        "Dasarahalli",
        "Dasarahalli Main Road",
        "Dayananda Nagar",
        "Defence Colony - Bagalagunte",
        "Devanahalli",
        "Devanahalli Road",
        "Devarachikkanahalli",
        "Dodda Aalada Mara Road",
        "Dodda Banasvadi",
        "Doddaballapur",
        "Doddaballapur Road",
        "Doddabommasandra",
        "Doddenahalli",
        "Doddenakundi",
        "Dollars Colony",
        "Domlur",
        "Dommasandra",
        "Ejipura",
        "Electronic City Phase I",
        "Electronic City Phase II",
        "Frazer Town",
        "Gandhi Nagar",
        "Ganga Nagar",
        "Gauribidanur",
        "GM Palya",
        "Gottigere",
        "Gunjur",
        "Guttahalli",
        "HAL",
        "Hanumantha Nagar",
        "Haragadde",
        "Haralur Road",
        "Harlur",
        "Haudin Road",
        "HBR Layout",
        "Hebbal",
        "Hegde Nagar",
        "Hennur",
        "Hennur Road",
        "Hesaraghatta",
        "Hombegowda Nagar",
        "Hongasandra",
        "Hoodi",
        "Horamavu",
        "Hosa Road",
        "Hosakerehalli",
        "Hoskote",
        "Hoskote Malur Road",
        "Hosur Road",
        "HRBR Layout",
        "HSR Layout",
        "Hulimavu",
        "Huskur",
        "Huttanahalli",
        "Indira Nagar",
        "Infantry Road",
        "International Airport Road",
        "ISRO Layout",
        "ITPL",
        "IVC Road",
        "Jagadish Nagar",
        "Jagajeevanram Nagar",
        "Jakkur",
        "Jalahalli Cross",
        "Jalahalli East",
        "Jalahalli West",
        "Jangamakote",
        "Jaya Chamarajendra Nagar",
        "Jayamahal",
        "Jayanagar",
        "Jeevanbheema Nagar",
        "Jigani",
        "Jnana Ganga Nagar",
        "JP Nagar",
        "K R Puram",
        "Kadabagere",
        "Kadugodi",
        "Kadugondanahalli",
        "Kadusonnappanahalli",
        "Kaggadasapura",
        "kaikondrahalli",
        "Kalena Agrahara",
        "Kalkere",
        "Kalyan Nagar",
        "Kamala Nagar",
        "Kamanahalli",
        "Kammanahalli",
        "Kammasandra",
        "Kammasandra Agrahara",
        "Kanakapura",
        "Kanakapura Road",
        "Kannamangala",
        "Kasavanahalli",
        "Kasturi Nagar",
        "Kattigenahalli",
        "Kaval Byrasandra",
        "Kempapura",
        "Kempegowda Nagar",
        "Kengeri",
        "Kengeri Satellite Town",
        "Kodichikkanahalli",
        "Kodigehalli",
        "Kodihalli",
        "Kodipur",
        "Kogilu",
        "Kolar Road",
        "Kolar-Chikkaballapur Road",
        "Konanakunte",
        "Koppa",
        "Koramangala",
        "Kothanur",
        "Kudlu Gate",
        "Kumaraswamy Layout",
        "Kundalahalli",
        "Laggere",
        "lal bagh",
        "Langford Road",
        "Langford Town",
        "Lavelle Road",
        "LB Shastri Nagar",
        "Lingarajapuram",
        "Madiwala",
        "Magadi Road",
        "Mahadevapura",
        "Mahalakshmi Layout",
        "Majestic",
        "Mallathahalli",
        "Malleshpalya",
        "Malleshwaram",
        "Malur-Hosur Road",
        "Marathahalli",
        "Marathahalli ORR",
        "Margondanahalli",
        "Maruthi Nagar",
        "Maruthi Sevanagar",
        "Mathikere",
        "MG Road",
        "Mico Layout",
        "Millers Road",
        "MS Palya",
        "Murugeshpalya",
        "Mysore Road",
        "Nagarabhavi",
        "Nagarbhavi Circle",
        "Nagasandra",
        "Nagavara",
        "Nandi Hills",
        "Nandini Layout",
        "Narasapura",
        "National Highway ",
        "Neelasandra",
        "Nelamangala",
        "New BEL Road",
        "New Thippasandra",
        "NRI Layout",
        "Off Sarjapur road",
        "Old Airport Road",
        "Old Madras Road",
        "OMBR Layout",
        "Outer Ring Road",
        "Padmanabha Nagar",
        "Pai Layout",
        "Palace Road",
        "Panathur",
        "Panduranga Nagar",
        "Peenya",
        "Prashanth Nagar",
        "R.K. Hegde Nagar",
        "Race Course Road",
        "Ragavendra Nagar",
        "Raja Rajeshwari Nagar",
        "Rajaji Nagar",
        "Rajanukunte",
        "Ramamurthy Nagar",
        "Ramohalli",
        "Rayasandra",
        "Residency Road",
        "Rest House Road",
        "Richard's Park",
        "Richards Town",
        "Richmond Road",
        "Richmond Town",
        "RMV",
        "RMV ",
        "RMV Extension",
        "RT Nagar",
        "Sadashiva Nagar",
        "Sadduguntepalya",
        "Sahakara Nagar",
        "Sampangi Rama Nagar",
        "Sanjay Nagar",
        "Sarjapur",
        "Sarjapur Attibele Road",
        "Sarjapur Bagalur Road",
        "Sarjapur Outer Ring Road",
        "Sarjapur Road",
        "Seshadripuram",
        "Shanthi Nagar",
        "Shettihalli",
        "Shidalgatta",
        "Shivaji Nagar",
        "Silk Board",
        "Singanahalli",
        "Singasandra",
        "SMV Layout",
        "Solur",
        "Soundarya Layout",
        "Srinagar",
        "Srinivasa Nagar",
        "St. Johns Road",
        "Subramanyapura",
        "Sudhama Nagar",
        "Sunkadakatte",
        "T Dasarahalli",
        "Tavarekere-BTM",
        "TC Palya Road",
        "Thanisandra",
        "Thanisandra Main Road",
        "Thavarekere-Magadi Road",
        "Thippasandra",
        "Thubarahalli",
        "Thurahalli",
        "Tumkur Road",
        "Ullal",
        "Ulsoor",
        "Uttarahalli",
        "Varthur",
        "Varthur Road",
        "Vasanth Nagar",
        "Venkatapura",
        "Victoria Layout",
        "Vidyaranyapura",
        "Vignana Nagar",
        "Vijayanagar",
        "Vijaypura",
        "Vishweshwaraiah Layout",
        "Vittal Mallya Road",
        "Vittal Nagar",
        "Viveka Nagar",
        "Weavers Colony",
        "Wheeler Road",
        "Whitefield",
        "Whitefield Road",
        "Williams Town",
        "Wilson Garden",
        "Wind Tunnel Road",
        "Yelachena Halli",
        "Yelahanka",
        "Yelahanka New Town",
        "Yemalur",
        "Yeshwanthpur"
    };

    public static final String[] poojaNames = {
        "Akhand Ramayan Paath",
        "Bhoomi Puja",
        "Dhanteras Puja",
        "Durga Puja",
        "Ganpati Puja / Ganesh Chaturthi",
        "Gauri Puja",
        "Griha Pravesh Puja",
        "Hanuman Chalisa Paath",
        "Havan",
        "Kaal Bhairav Puja",
        "Kali Puja",
        "Krishna Puja",
        "Laxmi Puja",
        "Maha Mrityunjaya Jaap",
        "Maha Shivratri Puja",
        "Mata Ki Chowki",
        "Navratri Puja",
        "Rudrabhishek Puja",
        "Sarswati Puja - Vasant Panchami",
        "Satyanarayan Puja",
        "Shiv Puja",
        "Sundarkand Paath",
        "Vishwakarma Puja",
        "Vivah Puja"
    };

    public static final String[] casteNames = {
        "Brahmin",
        "Lingayat",
        "Gowda"
    };

    public static final String[] languageNames = {
        "Assamese",
        "Bengali",
        "Bodo",
        "Dogri",
        "Gujarati",
        "Hindi",
        "Kannada",
        "Kashmiri",
        "Konkani",
        "Maithili",
        "Malayalam",
        "Manipuri",
        "Marathi",
        "Nepali",
        "Odia",
        "Punjabi",
        "Sanskrit",
        "Santali",
        "Sindhi",
        "Tamil",
        "Telugu"
    };

    public static final String[] monthNames = {
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"
    };

    public static final String[] timeNames = {
        "12AM - 1AM",
        "1AM - 2AM",
        "2AM - 3AM",
        "3AM - 4AM",
        "4AM - 5AM",
        "5AM - 6AM",
        "6AM - 7AM",
        "7AM - 8AM",
        "8AM - 9AM",
        "9AM - 10AM",
        "10AM - 11AM",
        "11AM - 12PM",
        "12PM - 1PM",
        "1PM - 2PM",
        "2PM - 3PM",
        "3PM - 4PM",
        "4PM - 5PM",
        "5PM - 6PM",
        "6PM - 7PM",
        "7PM - 8PM",
        "8PM - 9PM",
        "9PM - 10PM",
        "10PM - 11PM",
        "11PM - 12AM"
    };
}
